WIP: fix(KFLUXUI-253): tekton results should filter unknown status record out
konflux-ci/konflux-ui pull request #55
Opened 2024-12-13 13:49 UTC by testcara

2024-12-14 02:19 UTC, testcara commented
/retest

2025-01-08 06:11 UTC, sahil143 commented on src/utils/tekton-results.ts
> +};
Is it possible that an unknown status will appear for the pipeline runs that were not deleted? In that case, It's not a good idea to filter out the `Unknown` status pipeline runs.

2025-01-08 16:21 UTC, StanislavJochman commented on src/utils/tekton-results.ts
> +};
Can you specify why it is not good idea?

2025-01-09 07:04 UTC, testcara commented on src/utils/tekton-results.ts
> +};
I just improved the filter condition to ensure it is more accurate and added more explanations. Could you help to review again? Thank you!

2025-01-13 09:58 UTC, StanislavJochman submitted a review, later dismissed

2025-01-27 21:56 UTC, CryptoRodeo submitted a review, later dismissed

2025-01-30 07:41 UTC, sahil143 requested changes

2025-01-30 07:41 UTC, sahil143 commented on src/utils/tekton-results.ts
> +};
It's not a good idea to just filter out the `Unknown` status because When a pipeline run is running, its Condition Succeeded status is initially unknown. If the pipeline is deleted while in this state, it is archived to Tekton results with the same 'unknown' status. So we will end up filtering out the Running pipelines also.

2025-02-04 03:11 UTC, testcara commented on src/utils/tekton-results.ts
> +};
For the regular running pipeline, it would be shown running well.  see the screenshot:
![Screenshot 2025-02-04 at 10 57 10](https://github.com/user-attachments/assets/996c51f7-03f8-4e8d-af4c-480f4a0abf6c)
We will not filter out regular running pipelines. You could try to rerun one test run like https://localhost:8080/workspaces/wlin-tenant/applications/test-unstopped-pipeline/pipelineruns/test-28bg4 to check the whole process.

The filter will not affect any regular process.
Just when we delete the running pipeline, the pipeline would be gone  and this is the expected behavior.


BTW, do you have better idea, if you would give more suggestion, let me do more improvement with better solution. 
Is it possible we ask other team to add some item in the general status of the pipeline?

2025-02-04 10:03 UTC, StanislavJochman commented on src/utils/tekton-results.ts
> +        (c) => !(c.status === 'Unknown' && c.type === 'Succeeded' && c.reason === 'Running'),
do not we have enum for this?

2025-02-11 12:46 UTC, sahil143 commented on src/utils/tekton-results.ts
> +};
Make sense, only Tekton results are being filtered here. can you add a few test cases for this with running status condition and other status condition.

2025-02-12 03:23 UTC, testcara commented
@sahil143 , more status have been added to the test. Thank you for your review. :-)

2025-02-13 11:23 UTC, sahil143 approved these changes

2025-02-17 14:14 UTC, merged